title: ARI-bench
description: Adversarial Robustness Index Benchmark Suite & Research Log
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# GitHub Pages configuration
url: "https://mailtotanvir.github.io"
baseurl: "/ari-bench"

header_pages:
  - index.md
  - docs/EVALUATION_TRACKS.md

markdown: kramdown
highlighter: rouge
